/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Certification } from "./Certification";
import { CertificationCountArgs } from "./CertificationCountArgs";
import { CertificationFindManyArgs } from "./CertificationFindManyArgs";
import { CertificationFindUniqueArgs } from "./CertificationFindUniqueArgs";
import { DeleteCertificationArgs } from "./DeleteCertificationArgs";
import { CertificationService } from "../certification.service";
@graphql.Resolver(() => Certification)
export class CertificationResolverBase {
  constructor(protected readonly service: CertificationService) {}

  async _certificationsMeta(
    @graphql.Args() args: CertificationCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Certification])
  async certifications(
    @graphql.Args() args: CertificationFindManyArgs
  ): Promise<Certification[]> {
    return this.service.certifications(args);
  }

  @graphql.Query(() => Certification, { nullable: true })
  async certification(
    @graphql.Args() args: CertificationFindUniqueArgs
  ): Promise<Certification | null> {
    const result = await this.service.certification(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Certification)
  async deleteCertification(
    @graphql.Args() args: DeleteCertificationArgs
  ): Promise<Certification | null> {
    try {
      return await this.service.deleteCertification(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
