/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { CertificationService } from "../certification.service";
import { CertificationCreateInput } from "./CertificationCreateInput";
import { Certification } from "./Certification";
import { CertificationFindManyArgs } from "./CertificationFindManyArgs";
import { CertificationWhereUniqueInput } from "./CertificationWhereUniqueInput";
import { CertificationUpdateInput } from "./CertificationUpdateInput";

export class CertificationControllerBase {
  constructor(protected readonly service: CertificationService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Certification })
  async createCertification(
    @common.Body() data: CertificationCreateInput
  ): Promise<Certification> {
    return await this.service.createCertification({
      data: data,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Certification] })
  @ApiNestedQuery(CertificationFindManyArgs)
  async certifications(
    @common.Req() request: Request
  ): Promise<Certification[]> {
    const args = plainToClass(CertificationFindManyArgs, request.query);
    return this.service.certifications({
      ...args,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Certification })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async certification(
    @common.Param() params: CertificationWhereUniqueInput
  ): Promise<Certification | null> {
    const result = await this.service.certification({
      where: params,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Certification })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateCertification(
    @common.Param() params: CertificationWhereUniqueInput,
    @common.Body() data: CertificationUpdateInput
  ): Promise<Certification | null> {
    try {
      return await this.service.updateCertification({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Certification })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteCertification(
    @common.Param() params: CertificationWhereUniqueInput
  ): Promise<Certification | null> {
    try {
      return await this.service.deleteCertification({
        where: params,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
